### ISSUE TITLE
change in insert device

### ISSUE THREAD

**Issue by sage92** [carlosb/solarplant#3]
En el recurso [Device](https://github.com/carlosb/celeste/blob/master/doc/API.md#device):

Agregar metodo para que se puedan insertar Devices de la siguiente forma y quitar `ClientId`:
```
{
    "autogen"  : bool,
    "DeviceId" : integer,
    "ClientId" : integer, // quitar esto
    "man" : string,
    "mod" : 
    [
        string,
        string,
        ... 
    ],
    "sn"  : string    
}
```

**Comment by cbritopacheco** [comment]
Sergio, el campo `mod` sirve para establecer el modelo del Device. Es decir, este campo debe ser cosas como: `Basico`, `Avanzado`, `Primero`, etc. Como sea, he agregado un campo llamado `models` que representa los modelos asociados. El formato final es este:
```
{
    "autogen"  : bool,
    "DeviceId" : integer,
    "ClientId" : integer, // quitar esto
    "man" : string,
    "mod" : string,
    "sn"  : string,

    "models" : 
    [
        string,
        string,
        ... 
    ]
}
```

**Comment by cbritopacheco** [comment]
Un ejemplo para insertar un dispositivo es este:

```
{
        "autogen"  : true,
        "man" : "Mulkin",
        "mod" : "Basico",
        "sn"  : "A001-3312-312B",

        "models" : [
            "Potenciometro",
            "Termometro"
        ]
    }
```

**Comment by cbritopacheco** [comment]
La funcionalidad se ha implementado en badf79e531d67390cd7d6beac9dea52e3ba25367. Correre el servidor para que me intentes mandar un dispositivo.

**Comment by cbritopacheco** [comment]
The feature has been tried and tested.
