### ISSUE TITLE
Crear método que permita obtener una cantidad acumulada de lecturas individuales

### ISSUE THREAD

**Issue by Hyuchiha** [carlosb/solarplant#4]
Crear API para obtener el acumulado de mediciones para un rango de fecha determinado. 
Las especificaciones del método son las siguientes:

Method:
```
GET
````
Request:
```
{
	"startDate": "dd/mm/yyyy",
	"endDate": "dd/mm/yyyy",
	"devices": ["id-1", "id-2"]
}
```
Response:
```
{
	"consumo": float
}
```

**Comment by cbritopacheco** [comment]
Kevin, he editado tu Issue para que se vea un poco mas claro. Dentro del formato de request tienes un arreglo `"devices"`. Debería responderte con varios consumos? Ejemplo:

Request:
```
{
	"startDate": "21/12/1995",
	"endDate": "22/12/1995",
	"devices": [12, 14, 15]
}
```

Response:
```
{
    "consumos": [
         45.2,
         34.1,
         76.8
}
```

Una ultima pregunta: El ID del Device sera  `DeviceId` o `sn`? Comentale a Sergio para que nos pongamos de acuerdo.

**Comment by Hyuchiha** [comment]
Seria mejor que devolvieras el acumulado de todos los devices que te envié, y te enviariamos en **sn** ya que ese es el que tenemos almacenado

**Comment by cbritopacheco** [comment]
@Hyuchiha He decidido cambiar el tipo de dato de `DeviceId` a `string`, en lugar de `integer`. Ahora me podrán mandar el número serial en el `DeviceId` en lugar de manejar dos claves únicas. Mas tarde se reflejara en la documentación. Para uds no es necesario conocer la diferencia a menos que se inserten datos. Ver Issue #5.

**Comment by cbritopacheco** [comment]
Kevin, he implementado tu request. El formato final es este:

**Método**
`GET`

**Request**
```
{
        "DeviceIds" : 
        [
            string,
            string,
            ...
        ],
        "ModelId" : string,
        "PointId" : string,
        "method" : "accumulated",

        "start" : string,
        "end" : string
}
```

**Response**
```
{
    "DeviceId1" : double,
    "DeviceId2" : double,
    ...
}
```

**Comment by cbritopacheco** [comment]
Un ejemplo es este:

**Request**
```
{
        "DeviceIds" : ["A001-3312-312B", "A002-3312-312B"],
        "ModelId" : "potenciometro",
        "PointId" : "consumo",

        "method" : "accumulated",
        "start" : "2017-12-19 17:18:20",
        "end" : "2017-12-19 20:18:20"
}
```

**Response**
```
{
    "A001-3312-312B": 3016.0,
    "A002-3312-312B": 1661.0
}
```

**Comment by cbritopacheco** [comment]
Tu petición ha sido implementada en 4b8a29209556f26293ef311bbd1286289bcbb13a.
