### ISSUE TITLE
On/Off usando GET

### ISSUE THREAD

**Issue by juan-negron** [carlosb/solarplant#6]
Crear un servicio para las acciones del encendido o apagado de un [Device](https://github.com/carlosb/celeste/blob/master/doc/API.md#device).

A la URL se le hace una petición `GET` y se le manda en un objeto JSON con el identificador del dispositvo.

**Request**
```
{
    "DeviceId": string
}
```
La petitción devuelve `"ON"` o `"OFF"` según el caso. Es decir:

**Response**
```
"ON"
```
o
```
"OFF"
```

**Comment by cbritopacheco** [comment]
Juan, he editado tu comentario para hacer mas claro el formato. Me coordinare con el equipo del CRM.

**Comment by cbritopacheco** [comment]
Bajo que URL te gustaría tener el servicio?

**Comment by juan-negron** [comment]
**URL**

`/celeste/device/status`

**Response Code**
OK

**Comment by joseramonc** [comment]
```
POST work.tohtics.com:3330/api/auth/ABC-DEF
Response: 200
{ "device_status": "on" }
```
`device_status` tambien va a poder ser `"off"` pero ahorita siempre va a regresar "on" hasta que se implementa esa parte.
ABC-DEF es el número de serie del dispositivo.
Los números de serie que hay en la BD son los que se van dando de alta desde el CRM.
En caso de que no coincida el número de serie regresaría 404

**Comment by cbritopacheco** [comment]
@JohannesNegron Tu petición ha sido implementada. Como sea, el formato final que te ofreceré es el siguiente, debido a que se planea tener otros campos en la respuesta que tal vez causen confusión si lo dejaramos como `status`.

## Formato

**URL**
`/celeste/device/status`

**Method**
`Method: GET`

**Request**
```
{
    "DeviceId" : string
}
```

**Response**
```
{
    "isPowerCut" : bool
}
```

**Comment by cbritopacheco** [comment]
## Ejemplo

**Request**
```
{
    "DeviceId" : "A002-3312-312B"
}
```

**Response**

```
{
    "isPowerCut": false
}
```

**Comment by cbritopacheco** [comment]
Feature implemented in abec85e1faf0536c1f2e95b668ab7bbf73ff13b7.
