### ISSUE TITLE
Respuesta del servidor al arduino

### ISSUE THREAD

**Issue by Rajiv91** [carlosb/solarplant#7]
Para la versión del MVP la respuesta del servidor de una request `POST` (en caso de que haya llegado bien el dato al servidor) debe ser inmediata y con el siguiente formato: 
- `200,1` en caso de que se quiera mantener encendido
- `200,0` en case de que se quiera apagar

**Comment by cbritopacheco** [comment]
Rajiv, puedes consultar el estado del dispositivo de la siguiente manera:

## Método
`GET`

## URI
`/device/status/`

## Request Body
```
{
    "DeviceId" : string
}
```

## Response

```
Status Code: OK
```

```
{
    "isPowerCut" : boolean
}
```

**Comment by cbritopacheco** [comment]
Para tu request en especifico, se ha implementado el siguiente recurso. Como sea, esta marcado como `[[deprecated]]`.

## Método
`GET`

## URI
`/device/status/arduino`

## Request Body
```
{
    "DeviceId" : string
}
```
## Response
```http
Status Code: OK
```

Para prendido:
```
1
```

Para apagado:
```
0
```
